# Generated by Django 4.0 on 2022-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriber',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
