# Generated by Django 4.0 on 2022-06-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipcomment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'tip comment', 'verbose_name_plural': 'tip comments'},
        ),
        migrations.RenameField(
            model_name='tipcomment',
            old_name='timestamp',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tipcomment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='tipcomment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tipcomment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tipcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tipcomment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tipcomment',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='tipcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
        ),
    ]
