# Generated by Django 4.0 on 2022-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='title',
        ),
        migrations.AddField(
            model_name='meme',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
